# Generated by Django 4.2.7 on 2024-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidstream',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
